favicon: null
name: Sweeney
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6570185762830079
  brandStrength: 0.7921147
  lightness: 0.4375
  brandColors:
    - '#FFFFFF'
    - '#2F322F'
    - '#6E6D65'
    - '#B47E65'
    - '#D7CF65'
  rhythmicContrast: 0.75
typography_spectrum: 0.81996
layout_spectrum: 0.5322581
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
