name: Just Being Sweeney
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56907
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75466154-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2F4239'
    - '#879B9A'
    - '#BDCEE0'
    - '#F39388'
    - '#39B3E8'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0
purpose: []
