name: Just Being Sweeney
favicon: null
layout_spectrum: 0
typography_spectrum: 0.81996
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2F4239'
    - '#879B9A'
    - '#BDCEE0'
    - '#F39388'
    - '#39B3E8'
  brandStrength: 0.4892473
  lightness: 0.7598566
  saturation: 0.6570186
  rhythmicContrast: 0.75
purpose: []
