name: Just Being Sweeney
favicon: null
layout_spectrum: 0.5322581
typography_spectrum: 0.81996
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#2F322F'
    - '#6E6D65'
    - '#B47E65'
    - '#D7CF65'
  brandStrength: 0.7921147
  lightness: 0.7598566
  saturation: 0.6570186
  rhythmicContrast: 0.75
purpose: []
